### ISSUE TITLE
Consider loading the MermaidConfig within the Mermaid Block

### ISSUE THREAD

**Issue by ichim-david** [plonegovbr/volto-code-block#13]
https://github.com/plonegovbr/volto-code-block/blob/main/src/index.js#L38

Due to the AppExtender this package loads on every pages an external js
regardless of the use or not of the functionality of the MermaidBlock.
Ideally, the resources should be loaded only when using the block keeping
resource loading slim and focused

**Comment by ichim-david** [comment]
@ericof might be worth investigating this issue I've raised

**Comment by ericof** [comment]
@sneridagh Any idea how I can handle this?

**Comment by ichim-david** [comment]
@ericof I'm no @sneridagh but I think one solution could be to simply try to load it on mount within the component using this technique
https://www.altcademy.com/blog/how-to-load-js-src-from-script-tag-in-reactjs/#using-useeffect-hook-to-load-external-js-files
This way you avoid adding something that is not used but loaded everywhere due to the AppExtras.
